# Custom Language File for Launcher Customizer

[ejs.app]
title = "Chilloutmc"

[ejs.landing]
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/V6SqbUVFA5"

[ejs.settings]
sourceGithubLink = "https://github.com/Kitieshka/chilloutmc"
supportLink = "https://github.com/Kitieshka/chilloutmc/issues"

[ejs.welcome]
welcomeHeader = "Добро пожаловать на Chilloutmc"
welcomeDescription = "Мы стараемся сохранять наше ламповое комьюнити таким, как оно есть на протяжении работы всего сервера, оставайся с нами"
welcomeDescCTA = "Вы находитесь всего в нескольких кликах от Chilloutmc."
